export const STATES = [
    'AL',
    'AK',
    'AZ',
    'AR',
    'CA',
    'CO',
    'CT',
    'DE',
    'FL',
    'GA',
    'HI',
    'ID',
    'IL',
    'IN',
    'IA',
    'KS',
    'KY',
    'LA',
    'ME',
    'MD',
    'MA',
    'MI',
    'MN',
    'MS',
    'MO',
    'MT',
    'NE',
    'NV',
    'NH',
    'NJ',
    'NM',
    'NY',
    'NC',
    'ND',
    'OH',
    'OK',
    'OR',
    'PA',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VT',
    'VA',
    'WA',
    'WV',
    'WI',
    'WY',
];

export const YEARS = ['2020', '2021', '2022', '2023', '2024'];

// TODO: Remove when connecting to BE query
export const DUMMY_TEAMS = [
    'Los Angeles Lakers',
    'Phoenix Suns',
    'Boston Celtics',
];

// TODO: Remove when connecting to BE query
export const DUMMY_PLAYOFF_ROUNDS = [
    { label: 'None', value: '' },
    { label: 'NBA Finals', value: 'NBA Finals' },
    { label: 'Conference Finals', value: 'Conference Finals' },
];

// TODO: Remove when connecting to BE query
export const DUMMY_PLAYERS = [
    'LeBron James',
    'Anthony Davis',
    "D'Angelo Russell",
    'Austin Reaves',
    'Jaxson Hayes',
    'Russell Westbrook',
    'Rajon Rondo',
    'Jayson Tatum',
    'Jaylen Brown',
    'Derrick White',
    'Al Hortford',
    'Kristaps Porzingis',
    'Jrue Holiday',
    'Kevin Durant',
];
